#!/usr/bin/env bash

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
--remote-debugging-port=9222 \
--user-data-dir=/tmp \
--no-default-browser-check \
--no-first-run \
--disable-default-apps \
--start-maximized
